name: check
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  format:
    runs-on: ubuntu-latest
    name: format
    steps:
      - uses: actions/checkout@v4
      - name: Install Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
      - run: npm run format:check
  svelte-check:
    runs-on: ubuntu-latest
    name: svelte-check
    steps:
      - uses: actions/checkout@v4
      - name: Install Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
      - run: npm run check
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    name: lts / build
    steps:
      - uses: actions/checkout@v4
      - name: Install Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
      - run: npm run build
